app/urls.py
# Create web/urls.py and paste the following
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "web"

urlpatterns = [
    path("", views.Purple.as_view(), name="purple"),
    path("form/", views.Forms.as_view(), name="forms"),
    path("icon/", views.Icons.as_view(), name="icons"),
    path("buttons/", views.Buttons.as_view(), name="buttons"),
    path("typography/", views.Typography.as_view(), name="typography"),
    path("charts/", views.Charts.as_view(), name="charts"),
    path("tables/", views.Tables.as_view(), name="tables"),
    path("error/", views.Error.as_view(), name="error"),

    path("book-create/", views.BookCreate.as_view(), name="bookcreate"),
    path("book-list/", views.BookList.as_view(), name="booklist"),
    path("book-detail/<str:pk>/", views.BookDetail.as_view(), name="bookdetail"),
    path("book-update/<str:pk>/", views.BookUpdate.as_view(), name="bookupdate"),
    path("book-delete/<str:pk>/", views.BookDelete.as_view(), name="bookdelete"),


    path("author-create/", views.authorCreate.as_view(), name="authorcreate"),
    path("author-list/", views.authorList.as_view(), name="authorlist"),
    path("author-detail/<str:pk>/", views.authorDetail.as_view(), name="authordetail"),
    path("author-update/<str:pk>/", views.authorUpdate.as_view(), name="authorupdate"),
    path("author-delete/<str:pk>/", views.authorDelete.as_view(), name="authordelete"),


    path("user-create/", views.userCreate.as_view(), name="usercreate"),
    path("user-list/", views.userList.as_view(), name="userlist"),
    path("user-update/<str:pk>/", views.userUpdate.as_view(), name="userupdate"),
    path("user-delete/<str:pk>/", views.userDelete.as_view(), name="userdelete"),


]

# from . import views
# from django.urls import path

# app_name='app'

# urlpatterns=[
#     path("",views.purple,name="purple"),
#     path("charts/",views.charts,name="charts"),
#     path("forms/",views.forms,name="forms"),
#     path("mdi/",views.icons,name="icons"),
#     path("login/",views.login,name="login"),
#     path("register/",views.register,name="register"),
#     path("tables/",views.tables,name="tables"),
#     path("buttons/",views.buttons,name="buttons"),
#     path("typography/",views.typography,name="typography"),

# ]

elibrary/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path ('admin/', admin.site.urls),
    path ('',include('app.urls',namespace="app")),
    path('accounts/', include('registration.backends.default.urls')),
    
    
    # path('tinymce/', include('tinymce.urls')),


]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/author_delete.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags  %}
{% block title %}Delete "{{object}}"{% endblock %}

{% block content %}

<div class="page-header">
  <h3 class="page-title"> Delete "{{object}}"</h3>
</div>

<div class="row">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <div class="buttons mt-5">
            <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/web/author_detail.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block title %}{{title}}{% endblock %}

{% block content %}

<div class="page-header">
    <h3 class="page-title">{{object}}</h3>
</div>

<div class="row">
    <div class="col-md-12 grid-margin stretch-card">
        <div class="card">
          <div class="card-header">
            <h4 class="card-title">{{object}}</h4>
          </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <tbody>
                          <!-- {% for name, value in object.get_fields %}
                            {% if value %}
                            <tr>
                              <td> {{title}} </td>
                              <td> {{ value }} </td>
                            </tr>
                            {% endif %}
                          {% endfor %} -->
                          <tr>
                            <td> {{object.name}} </td>
                           
                            <td> {{object.bio}} </td>
                            
                            <!-- <td> {{object.description}} </td> -->
                           
                          </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
              <div class="">
                <a href="{{object.get_update_url}}" class="btn btn-sm btn-light btn-outline-info mr-2">{% trans "Edit" %}</a>
                <a href="{{object.get_delete_url}}" class="btn btn-sm btn-light btn-outline-danger">{% trans "Delete" %}</a>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/web/author_form.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title"> {{object}}</h3>
  </div>
  
  <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

templates/web/author_list.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}



<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
           <a href="{% url 'web:purple' %}"><i class="mdi mdi-home"></i></a>
        </span> 
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:authorcreate' %}" class="btn btn-lg btn-gradient-primary">New </a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.name}} </td>
                                {% if request.user.is_superuser %}
                                <td>
                                  <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-eye"></i></a> 
                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <small class="mb-0">No  exists.</small>
                {% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/web/author_update.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title"> {{object}}</h3>
  </div>
  
  <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
          </form>
        </div>
      </div>
    </div>
  
  </div>

{% endblock content %}

templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Purple Admin</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'web/assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/assets/vendors/css/vendor.bundle.base.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'web/assets/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'web/assets/images/favicon.ico' %}" />

</head>

<body>

    <div class="container-scroller">

        {% include 'web/partials/_navbar.html' %}
        <div class="container-fluid page-body-wrapper">

            {% include 'web/partials/_sidebar.html' %}
            <div class="main-panel">
                <div class="content-wrapper">

                    {% block content %}

                    {% endblock content %}
                </div>
                {% include 'web/partials/_footer.html' %}
            </div>
        </div>
    </div>
    <!-- plugins:js -->
    <script src="{% static 'web/assets/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="{% static 'web/assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'web/assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'web/assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'web/assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'web/assets/js/misc.js' %}"></script>
    <script src="{% static 'web/assets/js/chart.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="{% static 'web/assets/js/dashboard.js' %}"></script>
    <script src="{% static 'web/assets/js/todolist.js' %}"></script>
    <!-- End custom js for this page -->
</body>
</html>

templates/web/book_delete.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags  %}
{% block title %}Delete "{{object}}"{% endblock %}

{% block content %}

<div class="page-header">
  <h3 class="page-title"> Delete "{{object}}"</h3>
</div>

<div class="row">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <div class="buttons mt-5">
            <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/web/book_form.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title"> {{object}}</h3>
  </div>
  
  <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
          </form>
        </div>
      </div>
    </div>
  
  </div>

{% endblock content %}

templates/web/book_list.html
{% extends 'web/base.html' %}
{% load static %}


{% block content %}

<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
            <i class="mdi mdi-home"></i>
        </span> {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{{object_list.0.new_link}}" class="btn btn-lg btn-gradient-primary">New </a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.title}} </td>
                                {% if request.user.is_superuser %}
                                <td>
                                  <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-eye"></i></a> 
                                    <a href="{{object.get_update_url}}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{{object.get_delete_url}}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <small class="mb-0">No  exists.</small>
                {% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/web/book_update.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title"> {{object}}</h3>
  </div>
  
  <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
          </form>
        </div>
      </div>
    </div>
  
  </div>

{% endblock content %}

templates/web/user_delete .html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags  %}
{% block title %}Delete "{{object}}"{% endblock %}

{% block content %}

<div class="page-header">
  <h3 class="page-title"> Delete "{{object}}"</h3>
</div>

<div class="row">
  <div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
          <div class="buttons mt-5">
            <button type="submit" class="btn btn-gradient-danger">{% trans "Yes, Delete." %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "No, Take me back" %}</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/web/user_list.html
{% extends 'web/base.html' %}
{% load static %}
{% block content %}



<div class="page-header">
    <h3 class="page-title">
        <span class="page-title-icon bg-gradient-primary text-white mr-2">
           <a href="{% url 'web:purple' %}"><i class="mdi mdi-home"></i></a>
        </span> {{title}}
    </h3>
    {% if request.user.is_superuser %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item active" aria-current="page">
                <a href="{% url 'web:usercreate' %}" class="btn btn-lg btn-gradient-primary">New </a>
            </li>
        </ul>
    </nav>
    {% endif %}
</div>
<div class="row">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                {% if object_list %}
                <div class="table-responsive">
                    <table class="table table-bordered table-hover border" style="width:100%;">
                        <thead>
                            <tr>
                                <th> # </th>
                                <th> name </th>
                                {% if request.user.is_superuser %}<th> Actions </th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for object in object_list %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td> {{object.username}} </td>
                                <td> {{object.email}} </td>
                                {% if request.user.is_superuser %}
                                <td>
                                  {% comment %} <a href="{{object.get_absolute_url}}" class="btn btn-sm btn-circle btn-primary"><i class="mdi mdi-eye"></i></a>  {% endcomment %}
                                    <a href="{% url 'web:userupdate' object.id %}" class="btn btn-sm btn-circle btn-info"><i class="mdi mdi-pencil"></i></a>
                                    <a href="{% url 'web:userdelete' object.id %}" class="btn btn-sm btn-circle btn-danger"><i class="mdi mdi-delete"></i></a>
                                </td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% else %}
                <small class="mb-0">No  exists.</small>
                {% endif %}
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/web/user_update.html
{% extends 'web/base.html' %}
{% load static i18n crispy_forms_tags %}
{% block content %}

<div class="page-header">
    <h3 class="page-title"> {{object}}</h3>
  </div>
  
  <div class="row">
    <div class="col-md-6 grid-margin stretch-card">
      <div class="card">
        <div class="card-body">
          <form class="forms-sample" method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-gradient-primary mr-2">{% trans "Save" %}</button>
            <button type="button" onclick="history.back()" class="btn btn-light btn-outline-secondary">{% trans "Cancel" %}</button>
          </form>
        </div>
      </div>
    </div>
  
  </div>

{% endblock content %}